// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InstaSearch
{
    internal sealed partial class Vsix
    {
        public const string Id = "InstaSearch.afd12677-0927-4942-840a-ceff4044fc02";
        public const string Name = "InstaSearch";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
